phpqa:
    tools:
        - php-cs-fixer:0
        - phpunit:0
        - psalm
        - security-checker:0
    output: cli

php-cs-fixer:
    config: .php-cs-fixer.dist.php

psalm:
    config: psalm.xml
