preset: symfony

linting: true

enabled:
  - concat_with_spaces
  - newline_after_open_tag
  - ordered_use
  - strict
  - strict_param
  - short_array_syntax
  - php_unit_construct
  - phpdoc_order

disabled:
  - concat_without_spaces
